import AppKit
import Foundation

struct WeightSpec {
    let slug: String
    let value: NSFont.Weight
}

let fileManager = FileManager.default
let root = URL(fileURLWithPath: fileManager.currentDirectoryPath)

// The name list is generated by scripts/sync-symbol-catalog.mjs from the OS.
// It is deliberately not written here: one list feeds both "the app knows this
// name" and "a picture for it exists", so the two cannot drift, and a future
// macOS regenerates the whole set in one command instead of someone hand-adding
// symbols one at a time.
let namesFile = root.appendingPathComponent("scripts/symbol-names.txt")
guard let namesText = try? String(contentsOf: namesFile, encoding: .utf8) else {
    print("missing scripts/symbol-names.txt — run: node scripts/sync-symbol-catalog.mjs")
    exit(1)
}
let symbols = namesText.split(separator: "\n").map(String.init)

// One weight only, and it is not just a size decision: Cloudflare Pages caps a
// deployment at 20,000 files, and four weights across 7,988 symbols is 31,952.
// `symbolWeight` in app/symbol-flow.tsx must name the same one.
let weights = [WeightSpec(slug: "bold", value: .bold)]

let outputDirectory = root.appendingPathComponent("public/symbols", isDirectory: true)
try fileManager.createDirectory(at: outputDirectory, withIntermediateDirectories: true)

func render(name: String, weight: WeightSpec, destination: URL) throws {
    guard let source = NSImage(systemSymbolName: name, accessibilityDescription: name) else {
        print("skip missing symbol: \(name)")
        return
    }

    let base = NSImage.SymbolConfiguration(pointSize: 72, weight: weight.value, scale: .large)
    let color = NSImage.SymbolConfiguration(hierarchicalColor: .white)
    guard let configured = source.withSymbolConfiguration(base.applying(color)) else {
        print("skip unconfigurable symbol: \(name)")
        return
    }

    // Sized to the job, not to a round number. The tile is capped at 125px and
    // the glyph takes 58% of its content box — about 65 CSS px — so 192px still
    // has headroom on a 3x phone screen. Every step above this doubles the
    // catalog for detail nothing can display: at 384px the full 7,988-symbol
    // set is 65 MB, at 192px it is 30 MB.
    let side = 192
    let canvas = NSSize(width: CGFloat(side), height: CGFloat(side))

    // Draw into RGBA. CoreGraphics has no grey+alpha bitmap context — asking
    // for one yields a context that accepts every drawing call and keeps
    // nothing, so the files come out blank with no error anywhere.
    guard let rgba = NSBitmapImageRep(
        bitmapDataPlanes: nil,
        pixelsWide: side,
        pixelsHigh: side,
        bitsPerSample: 8,
        samplesPerPixel: 4,
        hasAlpha: true,
        isPlanar: false,
        colorSpaceName: .deviceRGB,
        bytesPerRow: 0,
        bitsPerPixel: 0
    ) else {
        throw NSError(domain: "SFSymbolRenderer", code: 1)
    }

    rgba.size = canvas
    NSGraphicsContext.saveGraphicsState()
    guard let context = NSGraphicsContext(bitmapImageRep: rgba) else {
        throw NSError(domain: "SFSymbolRenderer", code: 2)
    }
    NSGraphicsContext.current = context
    context.imageInterpolation = .high
    NSColor.clear.setFill()
    NSRect(origin: .zero, size: canvas).fill()

    let sourceSize = configured.size
    // The art used to be drawn at 128 inside a 192 canvas, so a third of every
    // mask was transparent padding — the CSS asked for a 148px glyph and got a
    // 99px one. This leaves a hairline of bleed room and nothing more.
    let maxSide = CGFloat(side) * 0.927
    let scale = min(maxSide / max(sourceSize.width, 1), maxSide / max(sourceSize.height, 1))
    let drawSize = NSSize(width: sourceSize.width * scale, height: sourceSize.height * scale)
    let drawRect = NSRect(
        x: (canvas.width - drawSize.width) / 2,
        y: (canvas.height - drawSize.height) / 2,
        width: drawSize.width,
        height: drawSize.height
    )
    configured.draw(in: drawRect, from: .zero, operation: .sourceOver, fraction: 1)
    context.flushGraphics()
    NSGraphicsContext.restoreGraphicsState()

    // Repack as grey+alpha. A CSS mask reads the alpha channel and discards the
    // colour, so three of RGBA's four channels are dead weight on every file.
    // The grey channel is a constant, which costs almost nothing compressed.
    guard let mask = NSBitmapImageRep(
        bitmapDataPlanes: nil,
        pixelsWide: side,
        pixelsHigh: side,
        bitsPerSample: 8,
        samplesPerPixel: 2,
        hasAlpha: true,
        isPlanar: false,
        colorSpaceName: .deviceWhite,
        bytesPerRow: 0,
        bitsPerPixel: 0
    ), let source = rgba.bitmapData, let target = mask.bitmapData else {
        throw NSError(domain: "SFSymbolRenderer", code: 3)
    }

    let sourceStride = rgba.bytesPerRow
    let targetStride = mask.bytesPerRow
    for y in 0..<side {
        for x in 0..<side {
            target[y * targetStride + x * 2] = 255
            target[y * targetStride + x * 2 + 1] = source[y * sourceStride + x * 4 + 3]
        }
    }

    guard let png = mask.representation(using: .png, properties: [:]) else {
        throw NSError(domain: "SFSymbolRenderer", code: 4)
    }
    try png.write(to: destination)
}

var rendered = 0
var skipped: [String] = []
let started = Date()

// The mask set is 7,988 files and takes minutes; the favicon and the OG card
// below take under a second. `--icons-only` renders just those two, so working
// on the icon does not mean re-rendering the whole catalog to see the result.
let iconsOnly = CommandLine.arguments.contains("--icons-only")

if !iconsOnly {
    for symbol in symbols {
        for weight in weights {
            let file = outputDirectory.appendingPathComponent("\(symbol)--\(weight.slug).png")
            do {
                try render(name: symbol, weight: weight, destination: file)
                rendered += 1
            } catch {
                skipped.append(symbol)
            }
        }
    }

    print(String(format: "rendered %d / %d symbols in %.0fs", rendered, symbols.count, Date().timeIntervalSince(started)))
    if !skipped.isEmpty {
        print("skipped \(skipped.count): \(skipped.prefix(10).joined(separator: ", "))")
    }
}

/// The favicon is a finished icon, not a mask: a browser tab paints it over
/// chrome we do not control, so it cannot lean on the site's dark background.
/// It used to solve that with a dark rounded tile — a black square sitting in
/// every tab strip. Now it is just the eyes, the way 👀 is: `eyes` filled
/// white, `eyes.inverse` drawn over it in the site's ink, so the outline and
/// pupils hold the shape on light chrome while the white sclera holds it on
/// dark. Everything outside the glyph is transparent. The mask PNGs above
/// still would not work here — a mask has no colour of its own.
func renderFavicon(name: String, destination: URL, side: Int = 512) throws {
    func layer(_ symbol: String, _ color: NSColor) throws -> NSImage {
        guard let source = NSImage(systemSymbolName: symbol, accessibilityDescription: symbol) else {
            throw NSError(domain: "SFSymbolRenderer", code: 4)
        }
        let configuration = NSImage.SymbolConfiguration(pointSize: 256, weight: .regular, scale: .large)
            .applying(NSImage.SymbolConfiguration(hierarchicalColor: color))
        guard let configured = source.withSymbolConfiguration(configuration) else {
            throw NSError(domain: "SFSymbolRenderer", code: 5)
        }
        return configured
    }

    // --bg from globals.css, and it must be the *default* theme's --bg: a
    // favicon is drawn once and served to every reader, whichever palette they
    // picked. Ink & amber is the default, so #0d0d10 — it was #07090c, which is
    // midnight's, and midnight stopped being the default.
    let ink = NSColor(srgbRed: 0x0d / 255, green: 0x0d / 255, blue: 0x10 / 255, alpha: 1)
    let sclera = try layer(name, .white)
    let outline = try layer("\(name).inverse", ink)

    let canvas = NSSize(width: CGFloat(side), height: CGFloat(side))
    guard let bitmap = NSBitmapImageRep(
        bitmapDataPlanes: nil,
        pixelsWide: side,
        pixelsHigh: side,
        bitsPerSample: 8,
        samplesPerPixel: 4,
        hasAlpha: true,
        isPlanar: false,
        colorSpaceName: .deviceRGB,
        bytesPerRow: 0,
        bitsPerPixel: 0
    ) else { throw NSError(domain: "SFSymbolRenderer", code: 6) }

    bitmap.size = canvas
    NSGraphicsContext.saveGraphicsState()
    guard let context = NSGraphicsContext(bitmapImageRep: bitmap) else {
        throw NSError(domain: "SFSymbolRenderer", code: 7)
    }
    NSGraphicsContext.current = context
    context.imageInterpolation = .high

    NSColor.clear.setFill()
    NSRect(origin: .zero, size: canvas).fill()

    // Without a tile the glyph is the whole icon, so it gets nearly the whole
    // canvas — a 16px tab favicon has no pixels to spend on margin. `eyes` is
    // wide and short, so this is width-bound and the result sits centred with
    // transparent bands above and below.
    let inset = canvas.width * 0.05
    let available = canvas.width - inset * 2
    let sourceSize = sclera.size
    let scale = min(available / max(sourceSize.width, 1), available / max(sourceSize.height, 1))
    let drawSize = NSSize(width: sourceSize.width * scale, height: sourceSize.height * scale)
    let drawRect = NSRect(
        x: (canvas.width - drawSize.width) / 2,
        y: (canvas.height - drawSize.height) / 2,
        width: drawSize.width,
        height: drawSize.height
    )
    // Same rect for both layers: the two variants share one bounding box, so
    // the outline lands exactly on the fill.
    sclera.draw(in: drawRect, from: .zero, operation: .sourceOver, fraction: 1)
    outline.draw(in: drawRect, from: .zero, operation: .sourceOver, fraction: 1)
    context.flushGraphics()
    NSGraphicsContext.restoreGraphicsState()

    guard let png = bitmap.representation(using: .png, properties: [:]) else {
        throw NSError(domain: "SFSymbolRenderer", code: 8)
    }
    try png.write(to: destination)
}

// "eyes" is the base; renderFavicon draws "eyes.inverse" over it as the outline.
try renderFavicon(name: "eyes", destination: root.appendingPathComponent("public/favicon.png"))

/// Re-encodes a fully painted bitmap without its alpha channel.
///
/// The share card covers every one of its 756,000 pixels, so that channel is a
/// constant 255 — and measured, it was most of the file: 538 KB with it, 305 KB
/// without. (Not what you would guess: a constant plane ought to deflate to
/// nothing. It does not here, because AppKit writes *premultiplied* RGBA and
/// interleaves the samples, so the constant is smeared one byte in every four
/// through data the filters are trying to predict.)
///
/// It has to be a copy rather than a 24-bit drawing surface: CGBitmapContext has
/// no 24-bit RGB format, so `NSGraphicsContext(bitmapImageRep:)` returns nil and
/// the render dies. Draw in RGBA, drop the channel on the way out.
///
/// The favicon keeps its alpha — that one is transparent on purpose, because the
/// colour behind a browser tab is not ours to choose.
func withoutAlpha(_ source: NSBitmapImageRep) -> NSBitmapImageRep {
    guard
        let from = source.bitmapData,
        let target = NSBitmapImageRep(
            bitmapDataPlanes: nil,
            pixelsWide: source.pixelsWide,
            pixelsHigh: source.pixelsHigh,
            bitsPerSample: 8,
            samplesPerPixel: 3,
            hasAlpha: false,
            isPlanar: false,
            colorSpaceName: .deviceRGB,
            bytesPerRow: 0,
            bitsPerPixel: 0
        ),
        let to = target.bitmapData
    else { return source }

    let samples = source.samplesPerPixel
    for y in 0 ..< source.pixelsHigh {
        var read = y * source.bytesPerRow
        var write = y * target.bytesPerRow
        for _ in 0 ..< source.pixelsWide {
            to[write] = from[read]
            to[write + 1] = from[read + 1]
            to[write + 2] = from[read + 2]
            read += samples
            write += 3
        }
    }

    return target
}

/// The link preview card. Drawn here rather than in a design tool so it cannot
/// drift from the product: same mark, same palette, same symbols the site
/// actually ships. A PNG exported from a design file would be a second thing in
/// `public/` that nothing can regenerate, and it would go stale in silence.
/// 1200x630 is the size every chat app crops to.
///
/// The composition is the site's own reading order turned sideways: on the left
/// the thing somebody else handed you — a reply, redacted, with three symbol
/// names selected out of it — and on the right what it turns into, the name of
/// this tool and those three symbols drawn for real. The reply is cropped by
/// the left and bottom edges on purpose. It is a fragment of something longer,
/// and a card that fitted the whole reply inside a tidy box would be claiming
/// the AI only ever says three words.
///
/// Every number below is in top-left coordinates, because that is how the
/// layout was measured; `place` flips them into AppKit's bottom-left.
func renderOpenGraph(destination: URL) throws {
    let width = 1200
    let height = 630
    let canvas = NSSize(width: CGFloat(width), height: CGFloat(height))

    guard let bitmap = NSBitmapImageRep(
        bitmapDataPlanes: nil,
        pixelsWide: width,
        pixelsHigh: height,
        bitsPerSample: 8,
        samplesPerPixel: 4,
        hasAlpha: true,
        isPlanar: false,
        colorSpaceName: .deviceRGB,
        bytesPerRow: 0,
        bitsPerPixel: 0
    ) else { throw NSError(domain: "SFSymbolRenderer", code: 9) }

    bitmap.size = canvas
    NSGraphicsContext.saveGraphicsState()
    guard let context = NSGraphicsContext(bitmapImageRep: bitmap) else {
        throw NSError(domain: "SFSymbolRenderer", code: 10)
    }
    NSGraphicsContext.current = context
    context.imageInterpolation = .high

    func place(_ x: CGFloat, _ y: CGFloat, _ w: CGFloat, _ h: CGFloat) -> NSRect {
        NSRect(x: x, y: canvas.height - y - h, width: w, height: h)
    }
    func ink(_ rgb: UInt32, _ alpha: CGFloat = 1) -> NSColor {
        NSColor(
            srgbRed: CGFloat((rgb >> 16) & 0xff) / 255,
            green: CGFloat((rgb >> 8) & 0xff) / 255,
            blue: CGFloat(rgb & 0xff) / 255,
            alpha: alpha
        )
    }

    // The default theme's raw values (ink & amber), not midnight's — one card is
    // served to everyone, and a reader who has not picked a palette gets this
    // one. **Re-run this script if those raw values ever move**; nothing else
    // notices. `--panel` and the two greys below are the same ones the site's
    // own input field is painted with.
    let bg = ink(0x0d0d10)          // --bg
    let panel = ink(0x212129)       // the reply's surface
    let hairline = ink(0x33333e)    // its border
    let redacted = ink(0x43434f)    // the blanked-out words
    let accent = ink(0xf5a524)      // --accent-rgb, the selection
    let selectionInk = ink(0x17171b)
    let bodyText = ink(0xf5f5f7)    // --text
    let mutedText = ink(0xadadb8)   // --muted

    bg.setFill()
    NSRect(origin: .zero, size: canvas).fill()

    // The card's alpha is higher than the page's for the same reason the symbols
    // are: this gets recompressed and shrunk to timeline size, and the page's
    // 0.1 does not survive that. It takes the **accent** hue rather than
    // --body-glow's dimmed (150,118,70), and that is the whole lesson from the
    // first attempt: a dimmed warm is a *desaturated* warm, and desaturated warm
    // lifted does not read as a lamp, it reads as dirt. Saturation is what buys
    // the alpha. It sits over the wordmark, not over the empty corner — in the
    // corner the same wash had nothing to light and read as a stain.
    // Three stops, not two. A two-stop radial across the full canvas falls off
    // so slowly that the whole right half goes brown — and a wash that broad
    // stops reading as light and starts reading as dirt, which is the same trap
    // the dimmed hue fell into. Reaching zero at 45% of the radius keeps the
    // glow tight around the wordmark; it still has to reach zero *inside* the
    // canvas, because clipping the fade — with a smaller rect, or an ellipse —
    // leaves a visible seam curving across the card.
    let glowStops: [(NSColor, CGFloat)] = [
        (ink(0xf5a524, 0.18), 0.0),
        (ink(0xf5a524, 0.06), 0.20),
        (ink(0xf5a524, 0.0), 0.45),
    ]
    if let glow = NSGradient(colorsAndLocations: glowStops[0], glowStops[1], glowStops[2]) {
        glow.draw(in: NSRect(origin: .zero, size: canvas), relativeCenterPosition: NSPoint(x: 0.5, y: 1))
    }

    func draw(symbol: String, rect: NSRect, color: NSColor, weight: NSFont.Weight = .bold) {
        guard let source = NSImage(systemSymbolName: symbol, accessibilityDescription: symbol) else { return }
        let configuration = NSImage.SymbolConfiguration(pointSize: 220, weight: weight, scale: .large)
            .applying(NSImage.SymbolConfiguration(hierarchicalColor: color))
        guard let art = source.withSymbolConfiguration(configuration) else { return }
        let size = art.size
        let scale = min(rect.width / max(size.width, 1), rect.height / max(size.height, 1))
        let drawn = NSSize(width: size.width * scale, height: size.height * scale)
        art.draw(
            in: NSRect(
                x: rect.midX - drawn.width / 2,
                y: rect.midY - drawn.height / 2,
                width: drawn.width,
                height: drawn.height
            ),
            from: .zero,
            operation: .sourceOver,
            fraction: 1
        )
    }

    // ---- the reply, cropped by the left and bottom edges ----

    let boxX: CGFloat = -164
    let boxY: CGFloat = 64
    let boxW: CGFloat = 628
    let boxH: CGFloat = 640
    let boxRect = place(boxX, boxY, boxW, boxH)
    let boxPath = NSBezierPath(roundedRect: boxRect, xRadius: 24, yRadius: 24)
    panel.setFill()
    boxPath.fill()

    // Deterministic: the blanked-out words are noise, but a card that reshuffled
    // itself on every render would make every rebuild a diff.
    var seed: UInt64 = 4471
    func random() -> CGFloat {
        seed = seed &* 6364136223846793005 &+ 1442695040888963407
        return CGFloat((seed >> 33) & 0xffffff) / CGFloat(0xffffff)
    }

    func bar(_ x: CGFloat, _ centerY: CGFloat, _ w: CGFloat) {
        redacted.setFill()
        let r = place(boxX + x, boxY + centerY - 6, w, 12)
        NSBezierPath(roundedRect: r, xRadius: 6, yRadius: 6).fill()
    }

    func fillRange(_ centerY: CGFloat, _ from: CGFloat, _ to: CGFloat) {
        var x = from
        while to - x > 60 {
            var w = 70 + random() * 170
            if w > to - x { w = to - x }
            bar(x, centerY, w)
            x += w + 20
            if random() < 0.15 { break }
        }
    }

    let chipFont = NSFont.systemFont(ofSize: 24, weight: .bold)
    let chipHeight = (chipFont.ascender - chipFont.descender).rounded() + 24

    /// One highlighted symbol name. Right-aligned, because the left end of every
    /// line is off the canvas.
    func chip(_ name: String, _ centerY: CGFloat, rightEdge: CGFloat) -> (x: CGFloat, width: CGFloat) {
        let label = NSAttributedString(string: name, attributes: [
            .font: chipFont,
            .foregroundColor: selectionInk,
        ])
        // Measured here rather than copied off the mock: the mock was set in
        // Inter, the system font is wider, and a hard-coded width clips the name
        // out of its own highlight.
        let labelSize = label.size()
        let w = labelSize.width.rounded() + 44
        let x = rightEdge - w
        let r = place(boxX + x, boxY + centerY - chipHeight / 2, w, chipHeight)
        accent.setFill()
        NSBezierPath(roundedRect: r, xRadius: 11, yRadius: 11).fill()
        label.draw(at: NSPoint(x: r.minX + 22, y: r.midY - labelSize.height / 2))
        return (x, w)
    }

    let names = ["square.and.arrow.up", "arrow.up.doc", "arrowshape.turn.up.right"]
    let chipRows: [Int: Int] = [2: 0, 6: 1, 10: 2]
    let chipRightEdges: [CGFloat] = [556, 486, 570]
    let contentRight = boxW - 40
    // Lines start past the cropped edge, so they read as continuing rather than
    // as a column that happens to begin at the frame.
    let bleedLeft: CGFloat = -40

    NSGraphicsContext.saveGraphicsState()
    boxPath.addClip()
    for row in 0 ... 13 {
        let centerY = 40 + 44 * CGFloat(row)
        guard let index = chipRows[row] else {
            fillRange(centerY, bleedLeft, contentRight)
            continue
        }
        let placed = chip(names[index], centerY, rightEdge: chipRightEdges[index])
        if placed.x - bleedLeft > 70 { fillRange(centerY, bleedLeft, placed.x - 20) }
        if contentRight - (placed.x + placed.width) > 70 {
            fillRange(centerY, placed.x + placed.width + 20, contentRight)
        }
    }
    NSGraphicsContext.restoreGraphicsState()

    hairline.setStroke()
    let boxStroke = NSBezierPath(roundedRect: boxRect.insetBy(dx: 1, dy: 1), xRadius: 23, yRadius: 23)
    boxStroke.lineWidth = 2
    boxStroke.stroke()

    // ---- what it turns into ----

    let columnX: CGFloat = 548
    // Three symbols and two gaps; the wordmark above is solved to this width.
    let glyphSide: CGFloat = 174
    let glyphPitch: CGFloat = 207
    let glyphRowWidth = glyphSide * 3 + (glyphPitch - glyphSide) * 2

    // The mark, on the same rounded tile as the header's. The fill is what
    // `.brand-mark` composites to in the browser — rgba(255,255,255,0.04) over
    // --shell #17171b — so the card's mark and the site's are the same colour,
    // not two guesses at "slightly lighter than the ground".
    let tile = place(columnX, 84, 76, 76)
    ink(0x202024).setFill()
    NSBezierPath(roundedRect: tile, xRadius: 18, yRadius: 18).fill()
    NSColor(white: 1, alpha: 0.14).setStroke()
    let tileStroke = NSBezierPath(roundedRect: tile.insetBy(dx: 0.5, dy: 0.5), xRadius: 18, yRadius: 18)
    tileStroke.lineWidth = 1
    tileStroke.stroke()
    // Two-tone, like the favicon and the header mark: one mark everywhere.
    let eyes = tile.insetBy(dx: 11.4, dy: 20)
    draw(symbol: "eyes", rect: eyes, color: .white)
    // Same colour the web mark's second layer takes: `.brand-glyph
    // .symbol-glyph + .symbol-glyph { color: var(--bg) }`.
    draw(symbol: "eyes.inverse", rect: eyes, color: bg)

    func write(_ string: String, font: NSFont, color: NSColor, tracking: CGFloat, x: CGFloat, bottom: CGFloat) {
        NSAttributedString(string: string, attributes: [
            .font: font,
            .foregroundColor: color,
            .kern: tracking,
        ]).draw(at: NSPoint(x: x, y: canvas.height - bottom))
    }

    // Sized to the row of symbols underneath rather than to a number: the two
    // are one block, and the mock was set in Inter while this renders in the
    // system font, which is narrower. Solving for the width keeps them flush
    // whatever the system font does next.
    let wordmark = "Better SF Symbols"
    let wordmarkTracking: CGFloat = -2
    func wordmarkWidth(_ size: CGFloat) -> CGFloat {
        NSAttributedString(string: wordmark, attributes: [
            .font: NSFont.systemFont(ofSize: size, weight: .semibold),
            .kern: wordmarkTracking,
        ]).size().width
    }
    var wordmarkSize: CGFloat = 70
    for _ in 0 ..< 6 {
        wordmarkSize *= glyphRowWidth / wordmarkWidth(wordmarkSize)
    }
    write(
        wordmark,
        font: .systemFont(ofSize: wordmarkSize.rounded(), weight: .semibold),
        color: bodyText,
        tracking: wordmarkTracking,
        x: columnX,
        bottom: 274
    )
    // The site's own tagline, `brand.tagline` in app/messages.ts, word for word.
    // The card used to run a line of its own ("Paste an AI reply…") and that is
    // one more place for the product to say two different things about itself.
    // English only, and not because the audience is: og:image is fetched by the
    // platform's crawler, not the reader's browser, and cached per URL — so a
    // per-locale card would be picked by whoever shared the link first and then
    // shown to everybody after them.
    write(
        "Catch them all. No more busywork 👋",
        font: .systemFont(ofSize: 27, weight: .regular),
        color: mutedText,
        tracking: 0,
        x: columnX,
        bottom: 336
    )

    // The three names from the reply, drawn. 0.927 is the same fraction the mask
    // pipeline uses inside its 192px canvas, so a symbol here is exactly the size
    // the same symbol is on a result tile.
    let bleed = glyphSide * (1 - 0.927) / 2
    for (index, name) in names.enumerated() {
        let cell = place(columnX + CGFloat(index) * glyphPitch, 386, glyphSide, glyphSide)
        draw(symbol: name, rect: cell.insetBy(dx: bleed, dy: bleed), color: .white)
    }

    context.flushGraphics()
    NSGraphicsContext.restoreGraphicsState()

    guard let png = withoutAlpha(bitmap).representation(using: .png, properties: [:]) else {
        throw NSError(domain: "SFSymbolRenderer", code: 11)
    }
    try png.write(to: destination)
}

try renderOpenGraph(destination: root.appendingPathComponent("public/og.png"))

print("Rendered SF Symbols into \(outputDirectory.path)")
