import AppKit
import Foundation

struct WeightSpec {
    let slug: String
    let value: NSFont.Weight
}

let fileManager = FileManager.default
let root = URL(fileURLWithPath: fileManager.currentDirectoryPath)

// The name list is generated by scripts/sync-symbol-catalog.mjs from the OS.
// It is deliberately not written here: one list feeds both "the app knows this
// name" and "a picture for it exists", so the two cannot drift, and a future
// macOS regenerates the whole set in one command instead of someone hand-adding
// symbols one at a time.
let namesFile = root.appendingPathComponent("scripts/symbol-names.txt")
guard let namesText = try? String(contentsOf: namesFile, encoding: .utf8) else {
    print("missing scripts/symbol-names.txt — run: node scripts/sync-symbol-catalog.mjs")
    exit(1)
}
let symbols = namesText.split(separator: "\n").map(String.init)

// One weight only, and it is not just a size decision: Cloudflare Pages caps a
// deployment at 20,000 files, and four weights across 7,988 symbols is 31,952.
// `symbolWeight` in app/symbol-flow.tsx must name the same one.
let weights = [WeightSpec(slug: "bold", value: .bold)]

let outputDirectory = root.appendingPathComponent("public/symbols", isDirectory: true)
try fileManager.createDirectory(at: outputDirectory, withIntermediateDirectories: true)

func render(name: String, weight: WeightSpec, destination: URL) throws {
    guard let source = NSImage(systemSymbolName: name, accessibilityDescription: name) else {
        print("skip missing symbol: \(name)")
        return
    }

    let base = NSImage.SymbolConfiguration(pointSize: 72, weight: weight.value, scale: .large)
    let color = NSImage.SymbolConfiguration(hierarchicalColor: .white)
    guard let configured = source.withSymbolConfiguration(base.applying(color)) else {
        print("skip unconfigurable symbol: \(name)")
        return
    }

    // Sized to the job, not to a round number. The tile is capped at 125px and
    // the glyph takes 58% of its content box — about 65 CSS px — so 192px still
    // has headroom on a 3x phone screen. Every step above this doubles the
    // catalog for detail nothing can display: at 384px the full 7,988-symbol
    // set is 65 MB, at 192px it is 30 MB.
    let side = 192
    let canvas = NSSize(width: CGFloat(side), height: CGFloat(side))

    // Draw into RGBA. CoreGraphics has no grey+alpha bitmap context — asking
    // for one yields a context that accepts every drawing call and keeps
    // nothing, so the files come out blank with no error anywhere.
    guard let rgba = NSBitmapImageRep(
        bitmapDataPlanes: nil,
        pixelsWide: side,
        pixelsHigh: side,
        bitsPerSample: 8,
        samplesPerPixel: 4,
        hasAlpha: true,
        isPlanar: false,
        colorSpaceName: .deviceRGB,
        bytesPerRow: 0,
        bitsPerPixel: 0
    ) else {
        throw NSError(domain: "SFSymbolRenderer", code: 1)
    }

    rgba.size = canvas
    NSGraphicsContext.saveGraphicsState()
    guard let context = NSGraphicsContext(bitmapImageRep: rgba) else {
        throw NSError(domain: "SFSymbolRenderer", code: 2)
    }
    NSGraphicsContext.current = context
    context.imageInterpolation = .high
    NSColor.clear.setFill()
    NSRect(origin: .zero, size: canvas).fill()

    let sourceSize = configured.size
    // The art used to be drawn at 128 inside a 192 canvas, so a third of every
    // mask was transparent padding — the CSS asked for a 148px glyph and got a
    // 99px one. This leaves a hairline of bleed room and nothing more.
    let maxSide = CGFloat(side) * 0.927
    let scale = min(maxSide / max(sourceSize.width, 1), maxSide / max(sourceSize.height, 1))
    let drawSize = NSSize(width: sourceSize.width * scale, height: sourceSize.height * scale)
    let drawRect = NSRect(
        x: (canvas.width - drawSize.width) / 2,
        y: (canvas.height - drawSize.height) / 2,
        width: drawSize.width,
        height: drawSize.height
    )
    configured.draw(in: drawRect, from: .zero, operation: .sourceOver, fraction: 1)
    context.flushGraphics()
    NSGraphicsContext.restoreGraphicsState()

    // Repack as grey+alpha. A CSS mask reads the alpha channel and discards the
    // colour, so three of RGBA's four channels are dead weight on every file.
    // The grey channel is a constant, which costs almost nothing compressed.
    guard let mask = NSBitmapImageRep(
        bitmapDataPlanes: nil,
        pixelsWide: side,
        pixelsHigh: side,
        bitsPerSample: 8,
        samplesPerPixel: 2,
        hasAlpha: true,
        isPlanar: false,
        colorSpaceName: .deviceWhite,
        bytesPerRow: 0,
        bitsPerPixel: 0
    ), let source = rgba.bitmapData, let target = mask.bitmapData else {
        throw NSError(domain: "SFSymbolRenderer", code: 3)
    }

    let sourceStride = rgba.bytesPerRow
    let targetStride = mask.bytesPerRow
    for y in 0..<side {
        for x in 0..<side {
            target[y * targetStride + x * 2] = 255
            target[y * targetStride + x * 2 + 1] = source[y * sourceStride + x * 4 + 3]
        }
    }

    guard let png = mask.representation(using: .png, properties: [:]) else {
        throw NSError(domain: "SFSymbolRenderer", code: 4)
    }
    try png.write(to: destination)
}

var rendered = 0
var skipped: [String] = []
let started = Date()

// The mask set is 7,988 files and takes minutes; the favicon and the OG card
// below take under a second. `--icons-only` renders just those two, so working
// on the icon does not mean re-rendering the whole catalog to see the result.
let iconsOnly = CommandLine.arguments.contains("--icons-only")

if !iconsOnly {
    for symbol in symbols {
        for weight in weights {
            let file = outputDirectory.appendingPathComponent("\(symbol)--\(weight.slug).png")
            do {
                try render(name: symbol, weight: weight, destination: file)
                rendered += 1
            } catch {
                skipped.append(symbol)
            }
        }
    }

    print(String(format: "rendered %d / %d symbols in %.0fs", rendered, symbols.count, Date().timeIntervalSince(started)))
    if !skipped.isEmpty {
        print("skipped \(skipped.count): \(skipped.prefix(10).joined(separator: ", "))")
    }
}

/// The favicon is a finished icon, not a mask: a browser tab paints it over
/// chrome we do not control, so it cannot lean on the site's dark background.
/// It used to solve that with a dark rounded tile — a black square sitting in
/// every tab strip. Now it is just the eyes, the way 👀 is: `eyes` filled
/// white, `eyes.inverse` drawn over it in the site's ink, so the outline and
/// pupils hold the shape on light chrome while the white sclera holds it on
/// dark. Everything outside the glyph is transparent. The mask PNGs above
/// still would not work here — a mask has no colour of its own.
func renderFavicon(name: String, destination: URL, side: Int = 512) throws {
    func layer(_ symbol: String, _ color: NSColor) throws -> NSImage {
        guard let source = NSImage(systemSymbolName: symbol, accessibilityDescription: symbol) else {
            throw NSError(domain: "SFSymbolRenderer", code: 4)
        }
        let configuration = NSImage.SymbolConfiguration(pointSize: 256, weight: .regular, scale: .large)
            .applying(NSImage.SymbolConfiguration(hierarchicalColor: color))
        guard let configured = source.withSymbolConfiguration(configuration) else {
            throw NSError(domain: "SFSymbolRenderer", code: 5)
        }
        return configured
    }

    // --bg from globals.css, and it must be the *default* theme's --bg: a
    // favicon is drawn once and served to every reader, whichever palette they
    // picked. Ink & amber is the default, so #0d0d10 — it was #07090c, which is
    // midnight's, and midnight stopped being the default.
    let ink = NSColor(srgbRed: 0x0d / 255, green: 0x0d / 255, blue: 0x10 / 255, alpha: 1)
    let sclera = try layer(name, .white)
    let outline = try layer("\(name).inverse", ink)

    let canvas = NSSize(width: CGFloat(side), height: CGFloat(side))
    guard let bitmap = NSBitmapImageRep(
        bitmapDataPlanes: nil,
        pixelsWide: side,
        pixelsHigh: side,
        bitsPerSample: 8,
        samplesPerPixel: 4,
        hasAlpha: true,
        isPlanar: false,
        colorSpaceName: .deviceRGB,
        bytesPerRow: 0,
        bitsPerPixel: 0
    ) else { throw NSError(domain: "SFSymbolRenderer", code: 6) }

    bitmap.size = canvas
    NSGraphicsContext.saveGraphicsState()
    guard let context = NSGraphicsContext(bitmapImageRep: bitmap) else {
        throw NSError(domain: "SFSymbolRenderer", code: 7)
    }
    NSGraphicsContext.current = context
    context.imageInterpolation = .high

    NSColor.clear.setFill()
    NSRect(origin: .zero, size: canvas).fill()

    // Without a tile the glyph is the whole icon, so it gets nearly the whole
    // canvas — a 16px tab favicon has no pixels to spend on margin. `eyes` is
    // wide and short, so this is width-bound and the result sits centred with
    // transparent bands above and below.
    let inset = canvas.width * 0.05
    let available = canvas.width - inset * 2
    let sourceSize = sclera.size
    let scale = min(available / max(sourceSize.width, 1), available / max(sourceSize.height, 1))
    let drawSize = NSSize(width: sourceSize.width * scale, height: sourceSize.height * scale)
    let drawRect = NSRect(
        x: (canvas.width - drawSize.width) / 2,
        y: (canvas.height - drawSize.height) / 2,
        width: drawSize.width,
        height: drawSize.height
    )
    // Same rect for both layers: the two variants share one bounding box, so
    // the outline lands exactly on the fill.
    sclera.draw(in: drawRect, from: .zero, operation: .sourceOver, fraction: 1)
    outline.draw(in: drawRect, from: .zero, operation: .sourceOver, fraction: 1)
    context.flushGraphics()
    NSGraphicsContext.restoreGraphicsState()

    guard let png = bitmap.representation(using: .png, properties: [:]) else {
        throw NSError(domain: "SFSymbolRenderer", code: 8)
    }
    try png.write(to: destination)
}

// "eyes" is the base; renderFavicon draws "eyes.inverse" over it as the outline.
try renderFavicon(name: "eyes", destination: root.appendingPathComponent("public/favicon.png"))

/// The link preview card. Drawn here rather than in a design tool so it cannot
/// drift from the product: same mark, same palette, same symbols the site
/// actually ships. 1200x630 is the size every chat app crops to.
/// Re-encodes a fully painted bitmap without its alpha channel.
///
/// The share card covers every one of its 756,000 pixels, so that channel is a
/// constant 255 — and measured, it was most of the file: 538 KB with it, 305 KB
/// without. (Not what you would guess: a constant plane ought to deflate to
/// nothing. It does not here, because AppKit writes *premultiplied* RGBA and
/// interleaves the samples, so the constant is smeared one byte in every four
/// through data the filters are trying to predict.)
///
/// It has to be a copy rather than a 24-bit drawing surface: CGBitmapContext has
/// no 24-bit RGB format, so `NSGraphicsContext(bitmapImageRep:)` returns nil and
/// the render dies. Draw in RGBA, drop the channel on the way out.
///
/// The favicon keeps its alpha — that one is transparent on purpose, because the
/// colour behind a browser tab is not ours to choose.
func withoutAlpha(_ source: NSBitmapImageRep) -> NSBitmapImageRep {
    guard
        let from = source.bitmapData,
        let target = NSBitmapImageRep(
            bitmapDataPlanes: nil,
            pixelsWide: source.pixelsWide,
            pixelsHigh: source.pixelsHigh,
            bitsPerSample: 8,
            samplesPerPixel: 3,
            hasAlpha: false,
            isPlanar: false,
            colorSpaceName: .deviceRGB,
            bytesPerRow: 0,
            bitsPerPixel: 0
        ),
        let to = target.bitmapData
    else { return source }

    let samples = source.samplesPerPixel
    for y in 0 ..< source.pixelsHigh {
        var read = y * source.bytesPerRow
        var write = y * target.bytesPerRow
        for _ in 0 ..< source.pixelsWide {
            to[write] = from[read]
            to[write + 1] = from[read + 1]
            to[write + 2] = from[read + 2]
            read += samples
            write += 3
        }
    }

    return target
}

func renderOpenGraph(destination: URL) throws {
    let width = 1200
    let height = 630
    let canvas = NSSize(width: CGFloat(width), height: CGFloat(height))

    guard let bitmap = NSBitmapImageRep(
        bitmapDataPlanes: nil,
        pixelsWide: width,
        pixelsHigh: height,
        bitsPerSample: 8,
        samplesPerPixel: 4,
        hasAlpha: true,
        isPlanar: false,
        colorSpaceName: .deviceRGB,
        bytesPerRow: 0,
        bitsPerPixel: 0
    ) else { throw NSError(domain: "SFSymbolRenderer", code: 9) }

    bitmap.size = canvas
    NSGraphicsContext.saveGraphicsState()
    guard let context = NSGraphicsContext(bitmapImageRep: bitmap) else {
        throw NSError(domain: "SFSymbolRenderer", code: 10)
    }
    NSGraphicsContext.current = context
    context.imageInterpolation = .high

    // The default theme's --bg and --body-glow (ink & amber), not midnight's —
    // one card is served to everyone, so it can only be the palette a reader
    // gets before they have picked one. **Re-run this script if the default
    // theme's raw values ever move**; nothing else notices.
    //
    // The glow is the card's own number, like the symbol band's — a share card
    // gets recompressed and shrunk to timeline size, and the page's 0.1 does not
    // survive that. But it takes the **accent** hue (245,165,36 = --accent-rgb)
    // rather than --body-glow's dimmed (150,118,70), and that is the whole
    // lesson from the first attempt: a dimmed warm is a *desaturated* warm, and
    // desaturated warm lifted 2.5x does not read as a lamp, it reads as dirt.
    // Midnight got away with the same lift because blue-grey at that level still
    // reads as a dark blue room. Saturation is what buys the alpha here.
    NSColor(srgbRed: 0x0d / 255, green: 0x0d / 255, blue: 0x10 / 255, alpha: 1).setFill()
    NSRect(origin: .zero, size: canvas).fill()
    if let glow = NSGradient(colors: [
        NSColor(srgbRed: 245 / 255, green: 165 / 255, blue: 36 / 255, alpha: 0.13),
        NSColor(srgbRed: 245 / 255, green: 165 / 255, blue: 36 / 255, alpha: 0),
    ]) {
        // Fill the whole canvas and push the centre to the top edge. Drawing
        // into a smaller rect clips the fade before it reaches zero, which
        // leaves a hard horizontal seam straight across the card.
        glow.draw(in: NSRect(origin: .zero, size: canvas), relativeCenterPosition: NSPoint(x: 0, y: 1))
    }

    func draw(symbol: String, rect: NSRect, color: NSColor, weight: NSFont.Weight = .bold) {
        guard let source = NSImage(systemSymbolName: symbol, accessibilityDescription: symbol) else { return }
        let configuration = NSImage.SymbolConfiguration(pointSize: 220, weight: weight, scale: .large)
            .applying(NSImage.SymbolConfiguration(hierarchicalColor: color))
        guard let art = source.withSymbolConfiguration(configuration) else { return }
        let size = art.size
        let scale = min(rect.width / max(size.width, 1), rect.height / max(size.height, 1))
        let drawn = NSSize(width: size.width * scale, height: size.height * scale)
        art.draw(
            in: NSRect(
                x: rect.midX - drawn.width / 2,
                y: rect.midY - drawn.height / 2,
                width: drawn.width,
                height: drawn.height
            ),
            from: .zero,
            operation: .sourceOver,
            fraction: 1
        )
    }

    // The mark, on the same rounded tile as the favicon. The fill is what
    // `.brand-mark` composites to in the browser — rgba(255,255,255,0.04) over
    // --shell #17171b — so the card's mark and the header's are the same
    // colour, not two guesses at "slightly lighter than the ground".
    let tile = NSRect(x: canvas.width / 2 - 66, y: 432, width: 132, height: 132)
    NSColor(srgbRed: 0x20 / 255, green: 0x20 / 255, blue: 0x24 / 255, alpha: 1).setFill()
    NSBezierPath(roundedRect: tile, xRadius: 30, yRadius: 30).fill()
    NSColor(srgbRed: 1, green: 1, blue: 1, alpha: 0.14).setStroke()
    let tileStroke = NSBezierPath(roundedRect: tile.insetBy(dx: 0.5, dy: 0.5), xRadius: 30, yRadius: 30)
    tileStroke.lineWidth = 1
    tileStroke.stroke()
    // Two-tone, like the favicon and the header mark: one mark everywhere.
    draw(symbol: "eyes", rect: tile.insetBy(dx: 26, dy: 40), color: .white)
    // Same colour the web mark's second layer takes: `.brand-glyph
    // .symbol-glyph + .symbol-glyph { color: var(--bg) }`.
    draw(
        symbol: "eyes.inverse",
        rect: tile.insetBy(dx: 26, dy: 40),
        color: NSColor(srgbRed: 0x0d / 255, green: 0x0d / 255, blue: 0x10 / 255, alpha: 1)
    )

    func centered(_ text: String, font: NSFont, color: NSColor, tracking: CGFloat, baseline: CGFloat) {
        let paragraph = NSMutableParagraphStyle()
        paragraph.alignment = .center
        let attributed = NSAttributedString(string: text, attributes: [
            .font: font,
            .foregroundColor: color,
            .kern: tracking,
            .paragraphStyle: paragraph,
        ])
        let size = attributed.size()
        attributed.draw(in: NSRect(x: 0, y: baseline, width: canvas.width, height: size.height + 8))
    }

    centered(
        "Better SF Symbols",
        font: NSFont.systemFont(ofSize: 78, weight: .semibold),
        // --text, not pure white: the page's brightest type is #f5f5f7.
        color: NSColor(srgbRed: 0xf5 / 255, green: 0xf5 / 255, blue: 0xf7 / 255, alpha: 1),
        tracking: -1.6,
        baseline: 320
    )
    // Three beats, and the last one is the correction: it said "Copy the code"
    // for months while the product copied the *name* by default — the card was
    // the last place still promising the wrong thing (CLAUDE.md, first line).
    // The middle beat carries the English title's phrase, so the tab, the
    // header and the share card all say one thing.
    centered(
        "Paste an AI reply. Preview them all. Copy the name.",
        font: NSFont.systemFont(ofSize: 31, weight: .regular),
        // --muted.
        color: NSColor(srgbRed: 0xad / 255, green: 0xad / 255, blue: 0xb8 / 255, alpha: 1),
        tracking: 0,
        baseline: 254
    )

    // A band of the real thing, so the card shows the product's subject. This
    // is the only element on the card that says "symbols" rather than "a name",
    // and at alpha 0.30 it did not survive being recompressed by X or WeChat
    // and shrunk to timeline size — the card read as a logo, not as a tool.
    let band = ["square.and.arrow.up", "paperplane", "photo.artframe", "gift", "arrow.up.circle", "hand.wave"]
    let cell: CGFloat = 96
    let spacing: CGFloat = 30
    let bandWidth = CGFloat(band.count) * cell + CGFloat(band.count - 1) * spacing
    var x = canvas.width / 2 - bandWidth / 2
    for symbol in band {
        draw(
            symbol: symbol,
            rect: NSRect(x: x, y: 92, width: cell, height: cell),
            color: NSColor(srgbRed: 1, green: 1, blue: 1, alpha: 0.55)
        )
        x += cell + spacing
    }

    context.flushGraphics()
    NSGraphicsContext.restoreGraphicsState()

    guard let png = withoutAlpha(bitmap).representation(using: .png, properties: [:]) else {
        throw NSError(domain: "SFSymbolRenderer", code: 11)
    }
    try png.write(to: destination)
}

try renderOpenGraph(destination: root.appendingPathComponent("public/og.png"))

print("Rendered SF Symbols into \(outputDirectory.path)")
